version: 2.1

jobs:
    Test2:
        docker:
            - image: kkiesling/pymoab-visit-py2-18.04
        steps:
            - checkout
            - run: pytest

    Test3:
        docker:
            - image: kkiesling/pymoab-visit-py3-18.04
        steps:
            - checkout
            - run: pytest

workflows:
    build:
        jobs:
            - Test2
            - Test3
